import React, { createContext, useContext, useState } from 'react';

export const translations = {
  el: {
    fleet: "ΣΤΟΛΟΣ",
    benefits: "ΠΑΡΟΧΕΣ",
    book_now: "ΚΡΑΤΗΣΗ",
    kos_greece: "Κως, Ελλάδα",
    hero_title_1: "Ανακαλύψτε την Κω",
    hero_title_2: "με τον δικό σας",
    hero_title_3: "ρυθμό.",
    hero_desc: "Απολαύστε τις πιο όμορφες διαδρομές του νησιού με απόλυτη ηρεμία και διαφάνεια. Άμεση παράδοση στο αεροδρόμιο, χωρίς κρυφές χρεώσεις και με ανθρώπινη, αξιόπιστη εξυπηρέτηση.",
    premium_experience: "Premium Εμπειρια στην Κω",
    happy_drivers: "500+ Ικανοποιημένοι Οδηγοί",
    instant_handover: "Άμεση Παράδοση",
    at_airport_hotel: "Στο Αεροδρόμιο ή το Ξενοδοχείο",
    zero_deposit: "0€ Εγγύηση",
    no_card_hold: "Χωρίς δέσμευση κάρτας.",
    full_insurance: "100% Μικτή",
    full_damage_cover: "Πλήρης κάλυψη ζημιών.",
    make_booking: "Κάντε Κράτηση",
    no_fees_pay_on_arrival: "Χωρίς χρέωση. Πληρώνετε στην παραλαβή.",
    name: "Ονομα",
    email: "Email",
    pickup_loc: "Παραλαβη",
    dropoff_loc: "Επιστροφη",
    select: "Επιλέξτε...",
    airport: "Αεροδρόμιο Κω (KGS)",
    port: "Λιμάνι Κω",
    hotel: "Ξενοδοχείο",
    pickup_date: "Ημ. & Ωρα Παραλαβης",
    dropoff_date: "Ημ. & Ωρα Επιστροφης",
    car_category: "Οχημα",
    gearbox: "Κιβωτιο",
    any: "Αδιάφορο",
    manual: "Χειροκίνητο",
    automatic: "Αυτόματο",
    send_request: "Αποστολη",
    processing: "Επεξεργασια...",
    request_sent: "Το αίτημά σας στάλθηκε!",
    contact_soon: "Θα επικοινωνήσουμε άμεσα.",
    new_booking: "Νεα Κρατηση",
    quick_book: "Γρηγορη Κρατηση",
    quick_book_desc: "Επιλέξτε όχημα και ημερομηνίες.",
    close: "Κλεισιμο",
    absolute_transparency: "Απόλυτη διαφάνεια.",
    no_hidden_fees: "Χωρίς κρυφές χρεώσεις, χωρίς εκπλήξεις. Ό,τι χρειάζεστε περιλαμβάνεται.",
    clear_pricing: "Ξεκάθαρη Τιμολόγηση",
    clear_pricing_desc: "Γνωρίζετε το ακριβές κόστος εξαρχής.",
    zero_deposit_title: "Μηδενική Εγγύηση",
    zero_deposit_desc: "Καμία δέσμευση στην πιστωτική σας κάρτα.",
    full_cover: "Πλήρης Κάλυψη",
    full_cover_desc: "Πλήρης μικτή ασφάλεια. Οδηγήστε με σιγουριά.",
    real_price: "Η Πραγματική Τιμή",
    compare_costs: "Δείτε την πραγματική διαφορά στο τελικό κόστος.",
    feature: "Παροχή",
    standard_rental: "Τυπική Ενοικίαση",
    base_price: "Βασική Τιμή",
    mixed_insurance: "Μικτή Ασφάλεια",
    included: "Περιλαμβάνεται",
    airport_delivery: "Παραλαβή / Επιστροφή Αεροδρόμιο",
    free: "Δωρεάν",
    card_hold: "Δέσμευση Πιστωτικής",
    final_cost: "Τελικό Κόστος",
    per_day: "/ ημ",
    our_fleet_new: "Διαθέσιμα Αυτοκίνητα",
    fleet_desc: "Όλα τα οχήματα συντηρούνται σχολαστικά και απολυμαίνονται πριν από κάθε ενοικίαση για την απόλυτη ασφάλειά σας.",
    included_title: "Στην τιμή περιλαμβάνονται:",
    inc_1: "Πλήρης ασφάλεια χωρίς απαλλαγή",
    inc_2: "Δεύτερος οδηγός",
    inc_3: "Παράδοση & παραλαβή στο αεροδρόμιο",
    inc_4: "Πολιτική καυσίμων full-to-full",
    inc_5: "Τηλέφωνο υποστήριξης 24/7",
    inc_6: "Καμία δέσμευση σε πιστωτική κάρτα",
    inc_footer: "Ό,τι βλέπεις, αυτό πληρώνεις.",
    passengers: "Επιβάτες",
    doors: "Πόρτες",
    ac: "A/C",
    no_excess: "Μικτή Χωρίς Απαλλαγή",
    free_delivery: "Δωρεάν Παράδοση",
    select_car: "Επιλογή",
    honest_choice: "Η ειλικρινής επιλογή για ενοικίαση αυτοκινήτου στην Κω.",
    contact: "Επικοινωνια",
    info: "Πληροφοριες",
    terms: "Όροι & Προϋποθέσεις",
    privacy: "Πολιτική Απορρήτου",
    faq: "Συχνές Ερωτήσεις",
    faq_q1: "Χρειάζομαι πιστωτική κάρτα για την ενοικίαση;",
    faq_a1: "Όχι, δεν απαιτείται πιστωτική κάρτα. Προσφέρουμε ενοικίαση με μηδενική εγγύηση και καμία δέσμευση ποσού στην κάρτα σας.",
    faq_q2: "Τι ακριβώς καλύπτει η μικτή ασφάλεια;",
    faq_a2: "Η μικτή ασφάλειά μας προσφέρει 100% κάλυψη ζημιών (συμπεριλαμβανομένων κρυστάλλων, καθρεπτών και ελαστικών) με μηδενική απαλλαγή (zero excess).",
    faq_q3: "Πού μπορώ να παραλάβω και να επιστρέψω το όχημα;",
    faq_a3: "Προσφέρουμε δωρεάν παράδοση και παραλαβή στο Αεροδρόμιο της Κω, στο λιμάνι και στα περισσότερα ξενοδοχεία του νησιού.",
    faq_q4: "Τι γίνεται σε περίπτωση καθυστέρησης της πτήσης μου;",
    faq_a4: "Παρακολουθούμε συνεχώς τις αφίξεις των πτήσεων. Το προσωπικό μας θα σας περιμένει την ώρα που θα προσγειωθείτε, χωρίς καμία επιπλέον χρέωση.",
    about_business_title: "Οικογενειακή Επιχείρηση στην Κω",
    about_business_desc: "Από το 1995, η Meltemi Rentals προσφέρει αξιόπιστες υπηρεσίες ενοικίασης με σεβασμό στον επισκέπτη. Χωρίς κρυφές χρεώσεις, με ανθρώπινη προσέγγιση.",
    all_rights: "All rights reserved.",
    reserve_your_car: "Κάντε Κράτηση",
    no_credit_card_fees: "Χωρίς πιστωτική κάρτα • Πληρωμή στην άφιξη",
    terms_desc: "Κάνοντας κράτηση οχήματος με την Meltemi Rentals, συμφωνείτε με τους παρακάτω όρους και προϋποθέσεις.",
    driver_requirements: "Απαιτήσεις Οδηγού",
    driver_req_desc: "Ο ενοικιαστής πρέπει να είναι τουλάχιστον 21 ετών και να διαθέτει έγκυρο δίπλωμα οδήγησης για τουλάχιστον 1 χρόνο.",
    insurance_coverage: "Ασφάλεια & Καλύψεις",
    insurance_cov_desc: "Οι τιμές μας περιλαμβάνουν πλήρη μικτή ασφάλεια (CDW) με μηδενική απαλλαγή. Καλύπτονται ζημιές σε ελαστικά, καθρέπτες και στο κάτω μέρος του αυτοκινήτου.",
    fuel_policy: "Πολιτική Καυσίμων",
    fuel_policy_desc: "Τα οχήματα πρέπει να επιστρέφονται με την ίδια ποσότητα καυσίμου που είχαν κατά την παραλαβή.",
    cancellations: "Ακυρώσεις",
    cancellations_desc: "Δωρεάν ακύρωση έως και 48 ώρες πριν την προγραμματισμένη ώρα παραλαβής.",
    privacy_desc: "Στη Meltemi Rentals, δεσμευόμαστε να προστατεύουμε το απόρρητο και τα προσωπικά σας δεδομένα.",
    data_collection: "Συλλογή Δεδομένων",
    data_coll_desc: "Συλλέγουμε τις απαραίτητες πληροφορίες, όπως το όνομά σας, τη διεύθυνση email, τον αριθμό τηλεφώνου και τις λεπτομέρειες της πτήσης, αποκλειστικά για την επεξεργασία της κράτησής σας και την ομαλή παράδοση.",
    data_usage: "Χρήση Δεδομένων",
    data_use_desc: "Τα δεδομένα σας δεν μοιράζονται ποτέ με τρίτους για σκοπούς μάρκετινγκ. Χρησιμοποιούνται αυστηρά για εσωτερική επικοινωνία, νομικά έγγραφα που απαιτούνται για την ενοικίαση οχημάτων και υποστήριξη πελατών.",
    security: "Ασφάλεια",
    security_desc: "Όλα τα δεδομένα που μεταδίδονται μέσω της ιστοσελίδας μας είναι κρυπτογραφημένα και αποθηκεύονται με ασφάλεια, σύμφωνα με τους τοπικούς κανονισμούς."
  },
  en: {
    fleet: "FLEET",
    benefits: "BENEFITS",
    book_now: "BOOK NOW",
    kos_greece: "Kos, Greece",
    hero_title_1: "Discover Kos Island",
    hero_title_2: "at your own",
    hero_title_3: "perfect pace.",
    hero_desc: "Explore the island's most scenic coastal roads, pristine beaches, and picturesque villages with total freedom. Honest all-inclusive rates and genuine local hospitality from the moment you arrive.",
    premium_experience: "Premium Experience in Kos",
    happy_drivers: "500+ Happy Drivers",
    instant_handover: "Instant Handover",
    at_airport_hotel: "At Airport or Hotel",
    zero_deposit: "0€ Deposit",
    no_card_hold: "No credit card hold.",
    full_insurance: "100% Full Ins.",
    full_damage_cover: "Full damage coverage.",
    make_booking: "Book Now",
    no_fees_pay_on_arrival: "No hidden fees. Pay on arrival.",
    name: "Name",
    email: "Email",
    pickup_loc: "Pick-up Loc",
    dropoff_loc: "Drop-off Loc",
    select: "Select...",
    airport: "Kos Airport (KGS)",
    port: "Kos Port",
    hotel: "Hotel",
    pickup_date: "Pick-up Time",
    dropoff_date: "Drop-off Time",
    car_category: "Vehicle",
    gearbox: "Gearbox",
    any: "Any",
    manual: "Manual",
    automatic: "Automatic",
    send_request: "Submit",
    processing: "Processing...",
    request_sent: "Request sent successfully!",
    contact_soon: "We will contact you shortly.",
    new_booking: "New Booking",
    quick_book: "Quick Book",
    quick_book_desc: "Select vehicle and dates.",
    close: "Close",
    absolute_transparency: "Absolute transparency.",
    no_hidden_fees: "No hidden fees, no surprises. Everything you need is included.",
    clear_pricing: "Clear Pricing",
    clear_pricing_desc: "You know the exact cost from the start.",
    zero_deposit_title: "Zero Deposit",
    zero_deposit_desc: "No credit card holds, for absolute peace of mind.",
    full_cover: "Full Coverage",
    full_cover_desc: "Full comprehensive insurance. Drive safely.",
    real_price: "The Real Price",
    compare_costs: "See the real difference in the final cost.",
    feature: "Feature",
    standard_rental: "Standard Rental",
    base_price: "Base Price",
    mixed_insurance: "Full Insurance",
    included: "Included",
    airport_delivery: "Airport Pickup / Drop-off",
    free: "Free",
    card_hold: "Credit Card Hold",
    final_cost: "Final Cost",
    per_day: "/ day",
    our_fleet_new: "Available Cars",
    fleet_desc: "Every vehicle is meticulously maintained and thoroughly sanitized before each rental for your complete safety.",
    included_title: "Included in the price:",
    inc_1: "Full insurance with zero excess",
    inc_2: "Second driver included",
    inc_3: "Airport delivery & collection",
    inc_4: "Full-to-full fuel policy",
    inc_5: "24/7 support line",
    inc_6: "No credit card hold",
    inc_footer: "What you see is what you pay.",
    passengers: "Passengers",
    doors: "Doors",
    ac: "A/C",
    no_excess: "Zero Excess",
    free_delivery: "Free Delivery",
    select_car: "Select",
    honest_choice: "The honest choice for car rental in Kos.",
    contact: "Contact",
    info: "Information",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    faq: "FAQ",
    faq_q1: "Do I need a credit card to rent a car?",
    faq_a1: "No, a credit card is not required. We offer zero deposit rentals with no holds on your card.",
    faq_q2: "What exactly does the full insurance cover?",
    faq_a2: "Our comprehensive insurance offers 100% damage coverage (including glass, mirrors, and tires) with zero excess.",
    faq_q3: "Where can I pick up and drop off the vehicle?",
    faq_a3: "We offer free delivery and collection at Kos Airport, the port, and most hotels on the island.",
    faq_q4: "What happens if my flight is delayed?",
    faq_a4: "We constantly monitor flight arrivals. Our staff will wait for you when you land, at no extra cost.",
    about_business_title: "Family Business in Kos",
    about_business_desc: "Since 1995, Meltemi Rentals has been offering reliable rental services with respect for our guests. No hidden fees, just a personal touch.",
    all_rights: "All rights reserved.",
    reserve_your_car: "Reserve your car",
    no_credit_card_fees: "No credit card fees • Pay on arrival",
    terms_desc: "By booking a vehicle with Meltemi Rentals, you agree to the following terms and conditions.",
    driver_requirements: "Driver Requirements",
    driver_req_desc: "The renter must be at least 21 years old and hold a valid driver's license for at least 1 year.",
    insurance_coverage: "Insurance & Coverage",
    insurance_cov_desc: "Our rates include full comprehensive insurance (CDW) with zero excess. Damage to tires, mirrors, and undercarriage is covered.",
    fuel_policy: "Fuel Policy",
    fuel_policy_desc: "Vehicles must be returned with the same amount of fuel as when they were picked up.",
    cancellations: "Cancellations",
    cancellations_desc: "Free cancellation up to 48 hours before the scheduled pickup time.",
    privacy_desc: "At Meltemi Rentals, we are committed to protecting your privacy and personal data.",
    data_collection: "Data Collection",
    data_coll_desc: "We collect necessary information such as your name, email address, phone number, and flight details exclusively for the purpose of processing your vehicle reservation and ensuring smooth delivery.",
    data_usage: "Data Usage",
    data_use_desc: "Your data is never shared with third parties for marketing purposes. It is strictly used for internal communication, legal documentation required for car rentals, and customer support.",
    security: "Security",
    security_desc: "All data transmitted through our website is encrypted and securely stored in compliance with local regulations."
  }
};

type Language = 'el' | 'en';
type Translations = typeof translations.el;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('el');

  const t = (key: keyof Translations) => {
    return translations[lang][key] || translations['el'][key];
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
